#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("hetodia.Resource", IsApplication=true)]

namespace hetodia
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int texto_gris = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int usuariodesc = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06004a
			public const int Alimentos = 2131099722;
			
			// aapt resource value: 0x7f06003b
			public const int Ejercicios = 2131099707;
			
			// aapt resource value: 0x7f060021
			public const int Serie = 2131099681;
			
			// aapt resource value: 0x7f060026
			public const int almuerzo = 2131099686;
			
			// aapt resource value: 0x7f060000
			public const int avanceEjercicios = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int buscadorAlimentos = 2131099657;
			
			// aapt resource value: 0x7f060038
			public const int buttonAerobicos = 2131099704;
			
			// aapt resource value: 0x7f06004c
			public const int buttonAgregarAvance = 2131099724;
			
			// aapt resource value: 0x7f060018
			public const int buttonAlmuerzo = 2131099672;
			
			// aapt resource value: 0x7f06003e
			public const int buttonAvanceEjercicios = 2131099710;
			
			// aapt resource value: 0x7f060019
			public const int buttonCena = 2131099673;
			
			// aapt resource value: 0x7f060082
			public const int buttonContinuar = 2131099778;
			
			// aapt resource value: 0x7f060017
			public const int buttonDesayuno = 2131099671;
			
			// aapt resource value: 0x7f060001
			public const int buttonEjercicio1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int buttonEjercicio2 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int buttonEjercicio3 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int buttonEjercicio4 = 2131099652;
			
			// aapt resource value: 0x7f06003a
			public const int buttonEstiramiento = 2131099706;
			
			// aapt resource value: 0x7f060039
			public const int buttonFuerza = 2131099705;
			
			// aapt resource value: 0x7f06006a
			public const int buttonGuardar = 2131099754;
			
			// aapt resource value: 0x7f060025
			public const int buttonGuardaraero = 2131099685;
			
			// aapt resource value: 0x7f060028
			public const int buttonGuardaralmu = 2131099688;
			
			// aapt resource value: 0x7f06002a
			public const int buttonGuardarcena = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int buttonGuardardes = 2131099691;
			
			// aapt resource value: 0x7f06002e
			public const int buttonGuardarfu = 2131099694;
			
			// aapt resource value: 0x7f060030
			public const int buttonGuardariso = 2131099696;
			
			// aapt resource value: 0x7f060052
			public const int buttonIngresar = 2131099730;
			
			// aapt resource value: 0x7f060006
			public const int buttonIrAGrafico = 2131099654;
			
			// aapt resource value: 0x7f06001c
			public const int buttonListaComida = 2131099676;
			
			// aapt resource value: 0x7f06003d
			public const int buttonListaEjercicios = 2131099709;
			
			// aapt resource value: 0x7f06003f
			public const int buttonMedicamento1 = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int buttonMedicamento2 = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int buttonMedicamento3 = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int buttonMedicamento4 = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int buttonMedicamento5 = 2131099715;
			
			// aapt resource value: 0x7f060080
			public const int buttonPerfilHepatico = 2131099776;
			
			// aapt resource value: 0x7f060081
			public const int buttonPerfilLipidico = 2131099777;
			
			// aapt resource value: 0x7f06001a
			public const int buttonSnack = 2131099674;
			
			// aapt resource value: 0x7f060076
			public const int buttonVerDieta = 2131099766;
			
			// aapt resource value: 0x7f060077
			public const int buttonVerEjercicios = 2131099767;
			
			// aapt resource value: 0x7f060078
			public const int buttonVerMedicamentos = 2131099768;
			
			// aapt resource value: 0x7f060048
			public const int buttonVerPacientes = 2131099720;
			
			// aapt resource value: 0x7f060029
			public const int cena = 2131099689;
			
			// aapt resource value: 0x7f060020
			public const int checkBoxAero1 = 2131099680;
			
			// aapt resource value: 0x7f060023
			public const int checkBoxAero2 = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int checkBoxAero3 = 2131099684;
			
			// aapt resource value: 0x7f06000b
			public const int configuracion = 2131099659;
			
			// aapt resource value: 0x7f060013
			public const int descripMedicamento = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int dieta = 2131099669;
			
			// aapt resource value: 0x7f06001b
			public const int dietaRegimen = 2131099675;
			
			// aapt resource value: 0x7f06004f
			public const int editText1 = 2131099727;
			
			// aapt resource value: 0x7f060051
			public const int editTextContraseña = 2131099729;
			
			// aapt resource value: 0x7f060034
			public const int ejercicio1 = 2131099700;
			
			// aapt resource value: 0x7f060037
			public const int ejercicios = 2131099703;
			
			// aapt resource value: 0x7f06002c
			public const int estiramiento = 2131099692;
			
			// aapt resource value: 0x7f060032
			public const int farmacia = 2131099698;
			
			// aapt resource value: 0x7f060072
			public const int frameLayout1 = 2131099762;
			
			// aapt resource value: 0x7f06002d
			public const int fuerza = 2131099693;
			
			// aapt resource value: 0x7f06001f
			public const int gridLayout1 = 2131099679;
			
			// aapt resource value: 0x7f06001d
			public const int gridLayout2 = 2131099677;
			
			// aapt resource value: 0x7f060044
			public const int gráfio = 2131099716;
			
			// aapt resource value: 0x7f060060
			public const int imageFotoPerfil = 2131099744;
			
			// aapt resource value: 0x7f060075
			public const int imageGrafico = 2131099765;
			
			// aapt resource value: 0x7f060045
			public const int imageView1 = 2131099717;
			
			// aapt resource value: 0x7f060055
			public const int imagenMono = 2131099733;
			
			// aapt resource value: 0x7f060035
			public const int imagenejercicio1 = 2131099701;
			
			// aapt resource value: 0x7f060007
			public const int inicio = 2131099655;
			
			// aapt resource value: 0x7f06002f
			public const int isometricos = 2131099695;
			
			// aapt resource value: 0x7f060031
			public const int linearLayout1 = 2131099697;
			
			// aapt resource value: 0x7f06004b
			public const int listaEjercicios = 2131099723;
			
			// aapt resource value: 0x7f060046
			public const int mensajeSaludo = 2131099718;
			
			// aapt resource value: 0x7f060058
			public const int mensajes = 2131099736;
			
			// aapt resource value: 0x7f06005b
			public const int menuDieta = 2131099739;
			
			// aapt resource value: 0x7f06005d
			public const int menuEjercicios = 2131099741;
			
			// aapt resource value: 0x7f06005c
			public const int menuMedicamentos = 2131099740;
			
			// aapt resource value: 0x7f06005a
			public const int menuPerfil = 2131099738;
			
			// aapt resource value: 0x7f060059
			public const int misDatosClinicos = 2131099737;
			
			// aapt resource value: 0x7f060057
			public const int pacientes = 2131099735;
			
			// aapt resource value: 0x7f06005e
			public const int perfil = 2131099742;
			
			// aapt resource value: 0x7f060056
			public const int perfilDoctor = 2131099734;
			
			// aapt resource value: 0x7f060071
			public const int perfilPaciente = 2131099761;
			
			// aapt resource value: 0x7f060012
			public const int radioButtonRotacion = 2131099666;
			
			// aapt resource value: 0x7f06007d
			public const int registroContraseña = 2131099773;
			
			// aapt resource value: 0x7f06007b
			public const int registroDireccion = 2131099771;
			
			// aapt resource value: 0x7f060087
			public const int registroEnfCro1 = 2131099783;
			
			// aapt resource value: 0x7f060088
			public const int registroEnfCro2 = 2131099784;
			
			// aapt resource value: 0x7f060089
			public const int registroEnfCro3 = 2131099785;
			
			// aapt resource value: 0x7f06007c
			public const int registroFechaNacimiento = 2131099772;
			
			// aapt resource value: 0x7f060084
			public const int registroHOMA = 2131099780;
			
			// aapt resource value: 0x7f060083
			public const int registroHbA1c = 2131099779;
			
			// aapt resource value: 0x7f06008a
			public const int registroLesionF1 = 2131099786;
			
			// aapt resource value: 0x7f06008b
			public const int registroLesionF2 = 2131099787;
			
			// aapt resource value: 0x7f06008c
			public const int registroLesionF3 = 2131099788;
			
			// aapt resource value: 0x7f06007e
			public const int registroPesoA = 2131099774;
			
			// aapt resource value: 0x7f06007f
			public const int registroPesoI = 2131099775;
			
			// aapt resource value: 0x7f060022
			public const int registroReaccionAlergica1 = 2131099682;
			
			// aapt resource value: 0x7f060085
			public const int registroReaccionAlergica2 = 2131099781;
			
			// aapt resource value: 0x7f060086
			public const int registroReaccionAlergica3 = 2131099782;
			
			// aapt resource value: 0x7f06007a
			public const int registronombre = 2131099770;
			
			// aapt resource value: 0x7f060008
			public const int searchPacientes = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int searchView1 = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int selecciontiempo = 2131099653;
			
			// aapt resource value: 0x7f060033
			public const int snack = 2131099699;
			
			// aapt resource value: 0x7f060027
			public const int spinner1 = 2131099687;
			
			// aapt resource value: 0x7f060011
			public const int spinnerAspecto = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int spinnerTamañoFuente = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int spinnerTipoFuente = 2131099661;
			
			// aapt resource value: 0x7f06006d
			public const int textALT = 2131099757;
			
			// aapt resource value: 0x7f06006e
			public const int textAST = 2131099758;
			
			// aapt resource value: 0x7f06006b
			public const int textAlbumina = 2131099755;
			
			// aapt resource value: 0x7f060068
			public const int textApoliproteinaA1 = 2131099752;
			
			// aapt resource value: 0x7f060069
			public const int textApoliproteínaB = 2131099753;
			
			// aapt resource value: 0x7f060070
			public const int textBilirrubina = 2131099760;
			
			// aapt resource value: 0x7f060050
			public const int textContraseña = 2131099728;
			
			// aapt resource value: 0x7f060074
			public const int textEdad = 2131099764;
			
			// aapt resource value: 0x7f06006c
			public const int textFosfatasaA = 2131099756;
			
			// aapt resource value: 0x7f060063
			public const int textHDL = 2131099747;
			
			// aapt resource value: 0x7f06004d
			public const int textHetodia = 2131099725;
			
			// aapt resource value: 0x7f060053
			public const int textHola = 2131099731;
			
			// aapt resource value: 0x7f060066
			public const int textHomocisteina = 2131099750;
			
			// aapt resource value: 0x7f060064
			public const int textLDL = 2131099748;
			
			// aapt resource value: 0x7f06003c
			public const int textMensajeMotivacional = 2131099708;
			
			// aapt resource value: 0x7f060073
			public const int textNombrePaciente = 2131099763;
			
			// aapt resource value: 0x7f060054
			public const int textNombreUsuario = 2131099732;
			
			// aapt resource value: 0x7f06005f
			public const int textPesoIdeal = 2131099743;
			
			// aapt resource value: 0x7f060067
			public const int textProteínaC = 2131099751;
			
			// aapt resource value: 0x7f06004e
			public const int textRut = 2131099726;
			
			// aapt resource value: 0x7f06006f
			public const int textTransaminasa = 2131099759;
			
			// aapt resource value: 0x7f060062
			public const int textTrigli = 2131099746;
			
			// aapt resource value: 0x7f060065
			public const int textVLDL = 2131099749;
			
			// aapt resource value: 0x7f060014
			public const int textView1 = 2131099668;
			
			// aapt resource value: 0x7f06001e
			public const int textView2 = 2131099678;
			
			// aapt resource value: 0x7f060016
			public const int textnombrePaciente = 2131099670;
			
			// aapt resource value: 0x7f060010
			public const int textoAspecto = 2131099664;
			
			// aapt resource value: 0x7f060049
			public const int textoCita = 2131099721;
			
			// aapt resource value: 0x7f060036
			public const int textoEjercicio1 = 2131099702;
			
			// aapt resource value: 0x7f060047
			public const int textoNombreDoctor = 2131099719;
			
			// aapt resource value: 0x7f060061
			public const int textoperfilLipídico = 2131099745;
			
			// aapt resource value: 0x7f06000e
			public const int textotamañoFuente = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int textotipoFuente = 2131099660;
			
			// aapt resource value: 0x7f060079
			public const int tituloMisDatosClini = 2131099769;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int avanceEjercicios = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int buscarPacientesDoc = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int busquedaAlimentoUsuario = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int configuracion = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int descripcionMedicamento = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dietaPacienteDoc = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dietaRegimen = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int edicionAerobicos = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int edicionAlmuerzo = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int edicionCena = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int edicionDesayuno = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int edicionEstiramiento = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int edicionFuerza = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int edicionIsometricos = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int edicionMedicamentos = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int edicionSnack = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ejercicio1Paciente = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ejercicioPacienteVisDoc = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ejercicios = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int farmacia = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int grafico = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int inicioDoctor = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int listaAlimentosUsuario = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int ListaEjercicios = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Login = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Main = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int menuDoctor = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int menuPaciente = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int perfilDelPaciente = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int perfilDoctorPaciente = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int PerfilHepatico = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int PerfilLipidico = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int perfilPacienteDoc = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int registroPaciente = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int registroPaciente2 = 2130903074;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
